const resturant = [
  {
    "image": "zomato image 1",
    "rest_name": "Fusion Feast",
    "rating": 1,
    "foodtypes": "Italian",
    "location": "Chandni Chowk",
    "price_for_two": 624,
    "distance_from_customer_house": 2.4,
    "offers": 3,
    "alcohol_serve": false,
    "resturant_open_time": 3,
    "resturant_close_time": 15
  },
  {
    "image": "zomato image 9",
    "rest_name": "Grill & Chill",
    "rating": 2,
    "foodtypes": "Korean",
    "location": "Rohini",
    "price_for_two": 867,
    "distance_from_customer_house": 5.5,
    "offers": 3,
    "alcohol_serve": false,
    "resturant_open_time": 22,
    "resturant_close_time": 10
  },
  {
    "image": "zomato image 10",
    "rest_name": "Grill & Chill",
    "rating": 3,
    "foodtypes": "Chinese",
    "location": "Saket",
    "price_for_two": 2348,
    "distance_from_customer_house": 4.4,
    "offers": 8,
    "alcohol_serve": false,
    "resturant_open_time": 8,
    "resturant_close_time": 20
  },
  {
    "image": "zomato image 7",
    "rest_name": "Savory Street",
    "rating": 5,
    "foodtypes": "Italian",
    "location": "Dwarka",
    "price_for_two": 1499,
    "distance_from_customer_house": 4.4,
    "offers": 29,
    "alcohol_serve": true,
    "resturant_open_time": 15,
    "resturant_close_time": 3
  },
  {
    "image": "zomato image 8",
    "rest_name": "Harvest Kitchen",
    "rating": 1,
    "foodtypes": "French",
    "location": "Hauz Khas",
    "price_for_two": 1599,
    "distance_from_customer_house": 4.2,
    "offers": 28,
    "alcohol_serve": false,
    "resturant_open_time": 2,
    "resturant_close_time": 14
  },
  {
    "image": "zomato image 5",
    "rest_name": "Urban Bites",
    "rating": 2,
    "foodtypes": "Korean",
    "location": "Lajpat Nagar",
    "price_for_two": 446,
    "distance_from_customer_house": 7.0,
    "offers": 18,
    "alcohol_serve": false,
    "resturant_open_time": 16,
    "resturant_close_time": 4
  },
  {
    "image": "zomato image 9",
    "rest_name": "Pepper & Plate",
    "rating": 1,
    "foodtypes": "Thai",
    "location": "Saket",
    "price_for_two": 1936,
    "distance_from_customer_house": 8.5,
    "offers": 1,
    "alcohol_serve": false,
    "resturant_open_time": 4,
    "resturant_close_time": 16
  },
  {
    "image": "zomato image 10",
    "rest_name": "Mountain Feast",
    "rating": 1,
    "foodtypes": "Korean",
    "location": "Vasant Kunj",
    "price_for_two": 1163,
    "distance_from_customer_house": 9.0,
    "offers": 11,
    "alcohol_serve": false,
    "resturant_open_time": 21,
    "resturant_close_time": 9
  },
  {
    "image": "zomato image 9",
    "rest_name": "Mountain Feast",
    "rating": 1,
    "foodtypes": "Japanese",
    "location": "Saket",
    "price_for_two": 1587,
    "distance_from_customer_house": 7.4,
    "offers": 11,
    "alcohol_serve": false,
    "resturant_open_time": 17,
    "resturant_close_time": 5
  },
  {
    "image": "zomato image 7",
    "rest_name": "Pepper & Plate",
    "rating": 4,
    "foodtypes": "Mexican",
    "location": "Chandni Chowk",
    "price_for_two": 1420,
    "distance_from_customer_house": 4.7,
    "offers": 26,
    "alcohol_serve": false,
    "resturant_open_time": 17,
    "resturant_close_time": 5
  },
  {
    "image": "zomato image 6",
    "rest_name": "The Rustic Table",
    "rating": 5,
    "foodtypes": "Chinese",
    "location": "Dwarka",
    "price_for_two": 1679,
    "distance_from_customer_house": 8.5,
    "offers": 8,
    "alcohol_serve": true,
    "resturant_open_time": 13,
    "resturant_close_time": 1
  },
  {
    "image": "zomato image 9",
    "rest_name": "Basil & Thyme",
    "rating": 4,
    "foodtypes": "American",
    "location": "Karol Bagh",
    "price_for_two": 1684,
    "distance_from_customer_house": 3.3,
    "offers": 0,
    "alcohol_serve": true,
    "resturant_open_time": 21,
    "resturant_close_time": 9
  },
  {
    "image": "zomato image 4",
    "rest_name": "Spice Garden",
    "rating": 5,
    "foodtypes": "French",
    "location": "Dwarka",
    "price_for_two": 670,
    "distance_from_customer_house": 4.8,
    "offers": 18,
    "alcohol_serve": false,
    "resturant_open_time": 14,
    "resturant_close_time": 2
  },
  {
    "image": "zomato image 1",
    "rest_name": "Spice Garden",
    "rating": 3,
    "foodtypes": "Italian",
    "location": "Vasant Kunj",
    "price_for_two": 2487,
    "distance_from_customer_house": 2.1,
    "offers": 24,
    "alcohol_serve": true,
    "resturant_open_time": 20,
    "resturant_close_time": 8
  },
  {
    "image": "zomato image 5",
    "rest_name": "Royal Curry House",
    "rating": 1,
    "foodtypes": "Thai",
    "location": "Vasant Kunj",
    "price_for_two": 483,
    "distance_from_customer_house": 7.0,
    "offers": 24,
    "alcohol_serve": true,
    "resturant_open_time": 23,
    "resturant_close_time": 11
  },
  {
    "image": "zomato image 7",
    "rest_name": "Savory Street",
    "rating": 3,
    "foodtypes": "Indian",
    "location": "Lajpat Nagar",
    "price_for_two": 1941,
    "distance_from_customer_house": 3.6,
    "offers": 13,
    "alcohol_serve": false,
    "resturant_open_time": 12,
    "resturant_close_time": 0
  },
  {
    "image": "zomato image 8",
    "rest_name": "Harvest Kitchen",
    "rating": 2,
    "foodtypes": "Italian",
    "location": "Karol Bagh",
    "price_for_two": 818,
    "distance_from_customer_house": 5.1,
    "offers": 3,
    "alcohol_serve": false,
    "resturant_open_time": 8,
    "resturant_close_time": 20
  },
  {
    "image": "zomato image 7",
    "rest_name": "The Tasty Corner",
    "rating": 1,
    "foodtypes": "Italian",
    "location": "Rohini",
    "price_for_two": 996,
    "distance_from_customer_house": 6.6,
    "offers": 12,
    "alcohol_serve": true,
    "resturant_open_time": 14,
    "resturant_close_time": 2
  },
  {
    "image": "zomato image 5",
    "rest_name": "The Hungry Panda",
    "rating": 1,
    "foodtypes": "Italian",
    "location": "Hauz Khas",
    "price_for_two": 1662,
    "distance_from_customer_house": 3.8,
    "offers": 13,
    "alcohol_serve": false,
    "resturant_open_time": 5,
    "resturant_close_time": 17
  },
  {
    "image": "zomato image 6",
    "rest_name": "The Rustic Table",
    "rating": 2,
    "foodtypes": "Mediterranean",
    "location": "Vasant Kunj",
    "price_for_two": 1641,
    "distance_from_customer_house": 8.1,
    "offers": 2,
    "alcohol_serve": true,
    "resturant_open_time": 21,
    "resturant_close_time": 9
  },
  {
    "image": "zomato image 5",
    "rest_name": "Royal Curry House",
    "rating": 4,
    "foodtypes": "Chinese",
    "location": "Dwarka",
    "price_for_two": 180,
    "distance_from_customer_house": 1.2,
    "offers": 30,
    "alcohol_serve": true,
    "resturant_open_time": 5,
    "resturant_close_time": 17
  },
  {
    "image": "zomato image 7",
    "rest_name": "Royal Curry House",
    "rating": 5,
    "foodtypes": "Italian",
    "location": "Vasant Kunj",
    "price_for_two": 696,
    "distance_from_customer_house": 8.8,
    "offers": 7,
    "alcohol_serve": true,
    "resturant_open_time": 23,
    "resturant_close_time": 11
  },
  {
    "image": "zomato image 2",
    "rest_name": "Midnight Biryani",
    "rating": 4,
    "foodtypes": "Korean",
    "location": "Saket",
    "price_for_two": 1755,
    "distance_from_customer_house": 5.6,
    "offers": 27,
    "alcohol_serve": false,
    "resturant_open_time": 15,
    "resturant_close_time": 3
  },
  {
    "image": "zomato image 9",
    "rest_name": "Harvest Kitchen",
    "rating": 1,
    "foodtypes": "Italian",
    "location": "Rohini",
    "price_for_two": 1692,
    "distance_from_customer_house": 10.6,
    "offers": 29,
    "alcohol_serve": true,
    "resturant_open_time": 3,
    "resturant_close_time": 15
  },
  {
    "image": "zomato image 2",
    "rest_name": "Crave & Savor",
    "rating": 3,
    "foodtypes": "Mexican",
    "location": "Dwarka",
    "price_for_two": 470,
    "distance_from_customer_house": 5.5,
    "offers": 28,
    "alcohol_serve": false,
    "resturant_open_time": 12,
    "resturant_close_time": 0
  },
  {
    "image": "zomato image 2",
    "rest_name": "Sizzling Spoon",
    "rating": 4,
    "foodtypes": "Thai",
    "location": "Connaught Place",
    "price_for_two": 547,
    "distance_from_customer_house": 1.8,
    "offers": 9,
    "alcohol_serve": false,
    "resturant_open_time": 11,
    "resturant_close_time": 23
  },
  {
    "image": "zomato image 4",
    "rest_name": "Harvest Kitchen",
    "rating": 4,
    "foodtypes": "Japanese",
    "location": "Rajouri Garden",
    "price_for_two": 1443,
    "distance_from_customer_house": 2.9,
    "offers": 8,
    "alcohol_serve": true,
    "resturant_open_time": 5,
    "resturant_close_time": 17
  },
  {
    "image": "zomato image 10",
    "rest_name": "Pepper & Plate",
    "rating": 1,
    "foodtypes": "Chinese",
    "location": "Chandni Chowk",
    "price_for_two": 1508,
    "distance_from_customer_house": 6.6,
    "offers": 5,
    "alcohol_serve": true,
    "resturant_open_time": 8,
    "resturant_close_time": 20
  },
  {
    "image": "zomato image 6",
    "rest_name": "Fusion Feast",
    "rating": 4,
    "foodtypes": "American",
    "location": "Saket",
    "price_for_two": 1839,
    "distance_from_customer_house": 10.6,
    "offers": 11,
    "alcohol_serve": false,
    "resturant_open_time": 12,
    "resturant_close_time": 0
  },
  {
    "image": "zomato image 4",
    "rest_name": "Golden Fork",
    "rating": 5,
    "foodtypes": "Thai",
    "location": "Vasant Kunj",
    "price_for_two": 1136,
    "distance_from_customer_house": 7.7,
    "offers": 8,
    "alcohol_serve": true,
    "resturant_open_time": 23,
    "resturant_close_time": 11
  },
  {
    "image": "zomato image 8",
    "rest_name": "Urban Bites",
    "rating": 2,
    "foodtypes": "Korean",
    "location": "Rohini",
    "price_for_two": 806,
    "distance_from_customer_house": 10.1,
    "offers": 5,
    "alcohol_serve": false,
    "resturant_open_time": 12,
    "resturant_close_time": 0
  },
  {
    "image": "zomato image 8",
    "rest_name": "Mountain Feast",
    "rating": 2,
    "foodtypes": "Japanese",
    "location": "Karol Bagh",
    "price_for_two": 175,
    "distance_from_customer_house": 9.8,
    "offers": 12,
    "alcohol_serve": true,
    "resturant_open_time": 14,
    "resturant_close_time": 2
  },
  {
    "image": "zomato image 7",
    "rest_name": "Basil & Thyme",
    "rating": 5,
    "foodtypes": "Indian",
    "location": "Chandni Chowk",
    "price_for_two": 898,
    "distance_from_customer_house": 2.0,
    "offers": 14,
    "alcohol_serve": true,
    "resturant_open_time": 7,
    "resturant_close_time": 19
  },
  {
    "image": "zomato image 8",
    "rest_name": "Pepper & Plate",
    "rating": 2,
    "foodtypes": "Korean",
    "location": "Vasant Kunj",
    "price_for_two": 1518,
    "distance_from_customer_house": 7.2,
    "offers": 23,
    "alcohol_serve": false,
    "resturant_open_time": 3,
    "resturant_close_time": 15
  },
  {
    "image": "zomato image 8",
    "rest_name": "The Tasty Corner",
    "rating": 3,
    "foodtypes": "Thai",
    "location": "Vasant Kunj",
    "price_for_two": 576,
    "distance_from_customer_house": 9.9,
    "offers": 26,
    "alcohol_serve": false,
    "resturant_open_time": 15,
    "resturant_close_time": 3
  },
  {
    "image": "zomato image 2",
    "rest_name": "Basil & Thyme",
    "rating": 4,
    "foodtypes": "American",
    "location": "Connaught Place",
    "price_for_two": 1887,
    "distance_from_customer_house": 3.8,
    "offers": 6,
    "alcohol_serve": false,
    "resturant_open_time": 11,
    "resturant_close_time": 23
  },
  {
    "image": "zomato image 4",
    "rest_name": "Crave & Savor",
    "rating": 2,
    "foodtypes": "Indian",
    "location": "Rohini",
    "price_for_two": 2106,
    "distance_from_customer_house": 8.0,
    "offers": 21,
    "alcohol_serve": true,
    "resturant_open_time": 5,
    "resturant_close_time": 17
  },
  {
    "image": "zomato image 1",
    "rest_name": "The Tasty Corner",
    "rating": 1,
    "foodtypes": "Indian",
    "location": "Rohini",
    "price_for_two": 2082,
    "distance_from_customer_house": 10.6,
    "offers": 9,
    "alcohol_serve": false,
    "resturant_open_time": 5,
    "resturant_close_time": 17
  },
  {
    "image": "zomato image 1",
    "rest_name": "Flavors of Heaven",
    "rating": 5,
    "foodtypes": "Mexican",
    "location": "Connaught Place",
    "price_for_two": 2186,
    "distance_from_customer_house": 3.1,
    "offers": 22,
    "alcohol_serve": false,
    "resturant_open_time": 9,
    "resturant_close_time": 21
  },
  {
    "image": "zomato image 6",
    "rest_name": "Flavors of Heaven",
    "rating": 1,
    "foodtypes": "Indian",
    "location": "Rohini",
    "price_for_two": 922,
    "distance_from_customer_house": 9.3,
    "offers": 18,
    "alcohol_serve": false,
    "resturant_open_time": 21,
    "resturant_close_time": 9
  },
  {
    "image": "zomato image 8",
    "rest_name": "Mountain Feast",
    "rating": 3,
    "foodtypes": "Thai",
    "location": "Vasant Kunj",
    "price_for_two": 758,
    "distance_from_customer_house": 5.4,
    "offers": 28,
    "alcohol_serve": false,
    "resturant_open_time": 13,
    "resturant_close_time": 1
  },
  {
    "image": "zomato image 9",
    "rest_name": "Sizzling Spoon",
    "rating": 5,
    "foodtypes": "Thai",
    "location": "Rohini",
    "price_for_two": 1211,
    "distance_from_customer_house": 2.0,
    "offers": 28,
    "alcohol_serve": true,
    "resturant_open_time": 6,
    "resturant_close_time": 18
  },
  {
    "image": "zomato image 6",
    "rest_name": "Flavors of Heaven",
    "rating": 2,
    "foodtypes": "Italian",
    "location": "Chandni Chowk",
    "price_for_two": 2300,
    "distance_from_customer_house": 5.6,
    "offers": 7,
    "alcohol_serve": true,
    "resturant_open_time": 20,
    "resturant_close_time": 8
  },
  {
    "image": "zomato image 1",
    "rest_name": "Mountain Feast",
    "rating": 4,
    "foodtypes": "Mediterranean",
    "location": "Hauz Khas",
    "price_for_two": 352,
    "distance_from_customer_house": 5.3,
    "offers": 26,
    "alcohol_serve": true,
    "resturant_open_time": 0,
    "resturant_close_time": 12
  },
  {
    "image": "zomato image 1",
    "rest_name": "Urban Bites",
    "rating": 2,
    "foodtypes": "Japanese",
    "location": "Lajpat Nagar",
    "price_for_two": 2358,
    "distance_from_customer_house": 3.8,
    "offers": 19,
    "alcohol_serve": true,
    "resturant_open_time": 17,
    "resturant_close_time": 5
  },
  {
    "image": "zomato image 2",
    "rest_name": "Midnight Biryani",
    "rating": 3,
    "foodtypes": "Italian",
    "location": "Dwarka",
    "price_for_two": 2153,
    "distance_from_customer_house": 9.3,
    "offers": 29,
    "alcohol_serve": true,
    "resturant_open_time": 10,
    "resturant_close_time": 22
  },
  {
    "image": "zomato image 9",
    "rest_name": "Royal Curry House",
    "rating": 3,
    "foodtypes": "American",
    "location": "Saket",
    "price_for_two": 2464,
    "distance_from_customer_house": 3.6,
    "offers": 15,
    "alcohol_serve": false,
    "resturant_open_time": 10,
    "resturant_close_time": 22
  },
  {
    "image": "zomato image 4",
    "rest_name": "Basil & Thyme",
    "rating": 2,
    "foodtypes": "Korean",
    "location": "Connaught Place",
    "price_for_two": 1208,
    "distance_from_customer_house": 2.4,
    "offers": 17,
    "alcohol_serve": false,
    "resturant_open_time": 12,
    "resturant_close_time": 0
  },
  {
    "image": "zomato image 2",
    "rest_name": "Grill & Chill",
    "rating": 1,
    "foodtypes": "Mediterranean",
    "location": "Chandni Chowk",
    "price_for_two": 2054,
    "distance_from_customer_house": 8.9,
    "offers": 20,
    "alcohol_serve": false,
    "resturant_open_time": 17,
    "resturant_close_time": 5
  },
  {
    "image": "zomato image 9",
    "rest_name": "Fusion Feast",
    "rating": 2,
    "foodtypes": "French",
    "location": "Lajpat Nagar",
    "price_for_two": 1968,
    "distance_from_customer_house": 10.8,
    "offers": 3,
    "alcohol_serve": true,
    "resturant_open_time": 12,
    "resturant_close_time": 0
  },
  {
    "image": "zomato image 2",
    "rest_name": "Coastal Curry",
    "rating": 1,
    "foodtypes": "Korean",
    "location": "Dwarka",
    "price_for_two": 1509,
    "distance_from_customer_house": 1.5,
    "offers": 16,
    "alcohol_serve": false,
    "resturant_open_time": 19,
    "resturant_close_time": 7
  },
  {
    "image": "zomato image 8",
    "rest_name": "Mountain Feast",
    "rating": 1,
    "foodtypes": "French",
    "location": "Rohini",
    "price_for_two": 1163,
    "distance_from_customer_house": 10.1,
    "offers": 11,
    "alcohol_serve": true,
    "resturant_open_time": 23,
    "resturant_close_time": 11
  },
  {
    "image": "zomato image 5",
    "rest_name": "Mountain Feast",
    "rating": 2,
    "foodtypes": "Chinese",
    "location": "Vasant Kunj",
    "price_for_two": 470,
    "distance_from_customer_house": 10.6,
    "offers": 14,
    "alcohol_serve": false,
    "resturant_open_time": 6,
    "resturant_close_time": 18
  },
  {
    "image": "zomato image 2",
    "rest_name": "Urban Bites",
    "rating": 4,
    "foodtypes": "Chinese",
    "location": "Saket",
    "price_for_two": 2321,
    "distance_from_customer_house": 8.7,
    "offers": 2,
    "alcohol_serve": false,
    "resturant_open_time": 7,
    "resturant_close_time": 19
  },
  {
    "image": "zomato image 8",
    "rest_name": "The Tasty Corner",
    "rating": 5,
    "foodtypes": "Mediterranean",
    "location": "Saket",
    "price_for_two": 762,
    "distance_from_customer_house": 6.3,
    "offers": 22,
    "alcohol_serve": false,
    "resturant_open_time": 9,
    "resturant_close_time": 21
  },
  {
    "image": "zomato image 7",
    "rest_name": "Golden Fork",
    "rating": 1,
    "foodtypes": "American",
    "location": "Chandni Chowk",
    "price_for_two": 549,
    "distance_from_customer_house": 9.0,
    "offers": 24,
    "alcohol_serve": false,
    "resturant_open_time": 7,
    "resturant_close_time": 19
  },
  {
    "image": "zomato image 2",
    "rest_name": "The Tasty Corner",
    "rating": 5,
    "foodtypes": "Japanese",
    "location": "Saket",
    "price_for_two": 2139,
    "distance_from_customer_house": 1.9,
    "offers": 5,
    "alcohol_serve": false,
    "resturant_open_time": 0,
    "resturant_close_time": 12
  },
  {
    "image": "zomato image 2",
    "rest_name": "Ocean Flavors",
    "rating": 5,
    "foodtypes": "Italian",
    "location": "Lajpat Nagar",
    "price_for_two": 1510,
    "distance_from_customer_house": 9.3,
    "offers": 27,
    "alcohol_serve": true,
    "resturant_open_time": 16,
    "resturant_close_time": 4
  },
  {
    "image": "zomato image 9",
    "rest_name": "Basil & Thyme",
    "rating": 4,
    "foodtypes": "Chinese",
    "location": "Karol Bagh",
    "price_for_two": 502,
    "distance_from_customer_house": 6.8,
    "offers": 3,
    "alcohol_serve": false,
    "resturant_open_time": 4,
    "resturant_close_time": 16
  },
  {
    "image": "zomato image 8",
    "rest_name": "Golden Fork",
    "rating": 3,
    "foodtypes": "French",
    "location": "Chandni Chowk",
    "price_for_two": 1953,
    "distance_from_customer_house": 1.7,
    "offers": 22,
    "alcohol_serve": false,
    "resturant_open_time": 21,
    "resturant_close_time": 9
  },
  {
    "image": "zomato image 10",
    "rest_name": "Urban Bites",
    "rating": 1,
    "foodtypes": "American",
    "location": "Rajouri Garden",
    "price_for_two": 810,
    "distance_from_customer_house": 9.4,
    "offers": 21,
    "alcohol_serve": true,
    "resturant_open_time": 13,
    "resturant_close_time": 1
  },
  {
    "image": "zomato image 5",
    "rest_name": "Urban Bites",
    "rating": 1,
    "foodtypes": "Japanese",
    "location": "Chandni Chowk",
    "price_for_two": 2076,
    "distance_from_customer_house": 7.6,
    "offers": 1,
    "alcohol_serve": false,
    "resturant_open_time": 21,
    "resturant_close_time": 9
  },
  {
    "image": "zomato image 2",
    "rest_name": "Golden Fork",
    "rating": 5,
    "foodtypes": "Mexican",
    "location": "Vasant Kunj",
    "price_for_two": 1371,
    "distance_from_customer_house": 10.5,
    "offers": 1,
    "alcohol_serve": false,
    "resturant_open_time": 7,
    "resturant_close_time": 19
  },
  {
    "image": "zomato image 10",
    "rest_name": "Golden Fork",
    "rating": 4,
    "foodtypes": "Mexican",
    "location": "Rohini",
    "price_for_two": 2411,
    "distance_from_customer_house": 1.6,
    "offers": 15,
    "alcohol_serve": false,
    "resturant_open_time": 9,
    "resturant_close_time": 21
  },
  {
    "image": "zomato image 7",
    "rest_name": "The Rustic Table",
    "rating": 2,
    "foodtypes": "Italian",
    "location": "Dwarka",
    "price_for_two": 109,
    "distance_from_customer_house": 6.5,
    "offers": 0,
    "alcohol_serve": true,
    "resturant_open_time": 7,
    "resturant_close_time": 19
  },
  {
    "image": "zomato image 10",
    "rest_name": "The Hungry Panda",
    "rating": 1,
    "foodtypes": "French",
    "location": "Lajpat Nagar",
    "price_for_two": 2304,
    "distance_from_customer_house": 2.0,
    "offers": 18,
    "alcohol_serve": true,
    "resturant_open_time": 3,
    "resturant_close_time": 15
  },
  {
    "image": "zomato image 1",
    "rest_name": "Urban Bites",
    "rating": 4,
    "foodtypes": "Italian",
    "location": "Rohini",
    "price_for_two": 538,
    "distance_from_customer_house": 6.2,
    "offers": 27,
    "alcohol_serve": false,
    "resturant_open_time": 6,
    "resturant_close_time": 18
  },
  {
    "image": "zomato image 7",
    "rest_name": "Grill & Chill",
    "rating": 1,
    "foodtypes": "Mexican",
    "location": "Vasant Kunj",
    "price_for_two": 2054,
    "distance_from_customer_house": 3.5,
    "offers": 25,
    "alcohol_serve": false,
    "resturant_open_time": 10,
    "resturant_close_time": 22
  },
  {
    "image": "zomato image 5",
    "rest_name": "The Hungry Panda",
    "rating": 1,
    "foodtypes": "Chinese",
    "location": "Saket",
    "price_for_two": 1953,
    "distance_from_customer_house": 11.0,
    "offers": 16,
    "alcohol_serve": false,
    "resturant_open_time": 7,
    "resturant_close_time": 19
  },
  {
    "image": "zomato image 7",
    "rest_name": "Urban Bites",
    "rating": 3,
    "foodtypes": "Mexican",
    "location": "Rohini",
    "price_for_two": 931,
    "distance_from_customer_house": 4.3,
    "offers": 12,
    "alcohol_serve": false,
    "resturant_open_time": 12,
    "resturant_close_time": 0
  },
  {
    "image": "zomato image 4",
    "rest_name": "Savory Street",
    "rating": 4,
    "foodtypes": "American",
    "location": "Rohini",
    "price_for_two": 369,
    "distance_from_customer_house": 8.9,
    "offers": 14,
    "alcohol_serve": false,
    "resturant_open_time": 16,
    "resturant_close_time": 4
  },
  {
    "image": "zomato image 4",
    "rest_name": "Royal Curry House",
    "rating": 4,
    "foodtypes": "Thai",
    "location": "Vasant Kunj",
    "price_for_two": 1251,
    "distance_from_customer_house": 2.7,
    "offers": 24,
    "alcohol_serve": true,
    "resturant_open_time": 2,
    "resturant_close_time": 14
  },
  {
    "image": "zomato image 2",
    "rest_name": "Grill & Chill",
    "rating": 5,
    "foodtypes": "Italian",
    "location": "Saket",
    "price_for_two": 1644,
    "distance_from_customer_house": 10.5,
    "offers": 4,
    "alcohol_serve": true,
    "resturant_open_time": 22,
    "resturant_close_time": 10
  },
  {
    "image": "zomato image 5",
    "rest_name": "Ocean Flavors",
    "rating": 4,
    "foodtypes": "Mexican",
    "location": "Hauz Khas",
    "price_for_two": 264,
    "distance_from_customer_house": 8.8,
    "offers": 3,
    "alcohol_serve": false,
    "resturant_open_time": 6,
    "resturant_close_time": 18
  },
  {
    "image": "zomato image 1",
    "rest_name": "Grill & Chill",
    "rating": 2,
    "foodtypes": "Japanese",
    "location": "Chandni Chowk",
    "price_for_two": 2223,
    "distance_from_customer_house": 9.3,
    "offers": 28,
    "alcohol_serve": false,
    "resturant_open_time": 17,
    "resturant_close_time": 5
  },
  {
    "image": "zomato image 1",
    "rest_name": "Pepper & Plate",
    "rating": 3,
    "foodtypes": "American",
    "location": "Saket",
    "price_for_two": 1137,
    "distance_from_customer_house": 8.2,
    "offers": 28,
    "alcohol_serve": false,
    "resturant_open_time": 8,
    "resturant_close_time": 20
  },
  {
    "image": "zomato image 7",
    "rest_name": "Spice Garden",
    "rating": 1,
    "foodtypes": "Mexican",
    "location": "Vasant Kunj",
    "price_for_two": 616,
    "distance_from_customer_house": 5.0,
    "offers": 22,
    "alcohol_serve": false,
    "resturant_open_time": 16,
    "resturant_close_time": 4
  },
  {
    "image": "zomato image 5",
    "rest_name": "Urban Bites",
    "rating": 2,
    "foodtypes": "Thai",
    "location": "Karol Bagh",
    "price_for_two": 782,
    "distance_from_customer_house": 4.1,
    "offers": 0,
    "alcohol_serve": true,
    "resturant_open_time": 18,
    "resturant_close_time": 6
  },
  {
    "image": "zomato image 9",
    "rest_name": "Ocean Flavors",
    "rating": 5,
    "foodtypes": "Italian",
    "location": "Saket",
    "price_for_two": 696,
    "distance_from_customer_house": 4.3,
    "offers": 17,
    "alcohol_serve": false,
    "resturant_open_time": 4,
    "resturant_close_time": 16
  },
  {
    "image": "zomato image 6",
    "rest_name": "Crave & Savor",
    "rating": 2,
    "foodtypes": "Japanese",
    "location": "Karol Bagh",
    "price_for_two": 1394,
    "distance_from_customer_house": 5.0,
    "offers": 27,
    "alcohol_serve": false,
    "resturant_open_time": 16,
    "resturant_close_time": 4
  },
  {
    "image": "zomato image 2",
    "rest_name": "Flavors of Heaven",
    "rating": 3,
    "foodtypes": "Mexican",
    "location": "Saket",
    "price_for_two": 559,
    "distance_from_customer_house": 9.7,
    "offers": 11,
    "alcohol_serve": false,
    "resturant_open_time": 13,
    "resturant_close_time": 1
  },
  {
    "image": "zomato image 9",
    "rest_name": "Sizzling Spoon",
    "rating": 5,
    "foodtypes": "Thai",
    "location": "Chandni Chowk",
    "price_for_two": 1851,
    "distance_from_customer_house": 9.7,
    "offers": 17,
    "alcohol_serve": false,
    "resturant_open_time": 18,
    "resturant_close_time": 6
  },
  {
    "image": "zomato image 9",
    "rest_name": "Royal Curry House",
    "rating": 4,
    "foodtypes": "French",
    "location": "Saket",
    "price_for_two": 1933,
    "distance_from_customer_house": 3.0,
    "offers": 21,
    "alcohol_serve": false,
    "resturant_open_time": 7,
    "resturant_close_time": 19
  },
  {
    "image": "zomato image 2",
    "rest_name": "Harvest Kitchen",
    "rating": 3,
    "foodtypes": "Mexican",
    "location": "Saket",
    "price_for_two": 1237,
    "distance_from_customer_house": 6.1,
    "offers": 28,
    "alcohol_serve": false,
    "resturant_open_time": 5,
    "resturant_close_time": 17
  },
  {
    "image": "zomato image 6",
    "rest_name": "Savory Street",
    "rating": 2,
    "foodtypes": "Mexican",
    "location": "Lajpat Nagar",
    "price_for_two": 1672,
    "distance_from_customer_house": 8.0,
    "offers": 9,
    "alcohol_serve": true,
    "resturant_open_time": 4,
    "resturant_close_time": 16
  },
  {
    "image": "zomato image 7",
    "rest_name": "Crave & Savor",
    "rating": 2,
    "foodtypes": "Indian",
    "location": "Connaught Place",
    "price_for_two": 2211,
    "distance_from_customer_house": 4.4,
    "offers": 29,
    "alcohol_serve": false,
    "resturant_open_time": 15,
    "resturant_close_time": 3
  },
  {
    "image": "zomato image 8",
    "rest_name": "The Tasty Corner",
    "rating": 4,
    "foodtypes": "Mediterranean",
    "location": "Chandni Chowk",
    "price_for_two": 1213,
    "distance_from_customer_house": 7.3,
    "offers": 22,
    "alcohol_serve": false,
    "resturant_open_time": 9,
    "resturant_close_time": 21
  },
  {
    "image": "zomato image 2",
    "rest_name": "Golden Fork",
    "rating": 4,
    "foodtypes": "Thai",
    "location": "Vasant Kunj",
    "price_for_two": 2057,
    "distance_from_customer_house": 1.3,
    "offers": 27,
    "alcohol_serve": true,
    "resturant_open_time": 9,
    "resturant_close_time": 21
  },
  {
    "image": "zomato image 1",
    "rest_name": "The Hungry Panda",
    "rating": 5,
    "foodtypes": "Japanese",
    "location": "Rohini",
    "price_for_two": 1480,
    "distance_from_customer_house": 8.5,
    "offers": 23,
    "alcohol_serve": false,
    "resturant_open_time": 20,
    "resturant_close_time": 8
  },
  {
    "image": "zomato image 2",
    "rest_name": "Pepper & Plate",
    "rating": 1,
    "foodtypes": "Japanese",
    "location": "Saket",
    "price_for_two": 1760,
    "distance_from_customer_house": 9.5,
    "offers": 25,
    "alcohol_serve": false,
    "resturant_open_time": 19,
    "resturant_close_time": 7
  },
  {
    "image": "zomato image 7",
    "rest_name": "Royal Curry House",
    "rating": 5,
    "foodtypes": "Mexican",
    "location": "Rajouri Garden",
    "price_for_two": 306,
    "distance_from_customer_house": 3.3,
    "offers": 9,
    "alcohol_serve": false,
    "resturant_open_time": 10,
    "resturant_close_time": 22
  },
  {
    "image": "zomato image 9",
    "rest_name": "Basil & Thyme",
    "rating": 2,
    "foodtypes": "Japanese",
    "location": "Chandni Chowk",
    "price_for_two": 2397,
    "distance_from_customer_house": 10.8,
    "offers": 9,
    "alcohol_serve": true,
    "resturant_open_time": 13,
    "resturant_close_time": 1
  },
  {
    "image": "zomato image 9",
    "rest_name": "Grill & Chill",
    "rating": 1,
    "foodtypes": "Chinese",
    "location": "Chandni Chowk",
    "price_for_two": 1526,
    "distance_from_customer_house": 8.8,
    "offers": 14,
    "alcohol_serve": true,
    "resturant_open_time": 1,
    "resturant_close_time": 13
  },
  {
    "image": "zomato image 4",
    "rest_name": "Flavors of Heaven",
    "rating": 2,
    "foodtypes": "Indian",
    "location": "Rajouri Garden",
    "price_for_two": 974,
    "distance_from_customer_house": 8.9,
    "offers": 12,
    "alcohol_serve": false,
    "resturant_open_time": 18,
    "resturant_close_time": 6
  },
  {
    "image": "zomato image 6",
    "rest_name": "Flavors of Heaven",
    "rating": 1,
    "foodtypes": "Korean",
    "location": "Hauz Khas",
    "price_for_two": 939,
    "distance_from_customer_house": 9.8,
    "offers": 21,
    "alcohol_serve": false,
    "resturant_open_time": 8,
    "resturant_close_time": 20
  },
  {
    "image": "zomato image 1",
    "rest_name": "Mountain Feast",
    "rating": 5,
    "foodtypes": "Indian",
    "location": "Saket",
    "price_for_two": 560,
    "distance_from_customer_house": 2.3,
    "offers": 18,
    "alcohol_serve": true,
    "resturant_open_time": 20,
    "resturant_close_time": 8
  },
  {
    "image": "zomato image 10",
    "rest_name": "Midnight Biryani",
    "rating": 1,
    "foodtypes": "Japanese",
    "location": "Connaught Place",
    "price_for_two": 969,
    "distance_from_customer_house": 10.8,
    "offers": 27,
    "alcohol_serve": false,
    "resturant_open_time": 17,
    "resturant_close_time": 5
  },
  {
    "image": "zomato image 8",
    "rest_name": "Sizzling Spoon",
    "rating": 4,
    "foodtypes": "Thai",
    "location": "Saket",
    "price_for_two": 2223,
    "distance_from_customer_house": 1.1,
    "offers": 4,
    "alcohol_serve": false,
    "resturant_open_time": 12,
    "resturant_close_time": 0
  },
  {
    "image": "zomato image 7",
    "rest_name": "Urban Bites",
    "rating": 1,
    "foodtypes": "Thai",
    "location": "Chandni Chowk",
    "price_for_two": 1560,
    "distance_from_customer_house": 3.8,
    "offers": 25,
    "alcohol_serve": false,
    "resturant_open_time": 3,
    "resturant_close_time": 15
  },
  {
    "image": "zomato image 9",
    "rest_name": "Fusion Feast",
    "rating": 1,
    "foodtypes": "Mexican",
    "location": "Connaught Place",
    "price_for_two": 1433,
    "distance_from_customer_house": 2.8,
    "offers": 14,
    "alcohol_serve": true,
    "resturant_open_time": 14,
    "resturant_close_time": 2
  }
]

